import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import { visualizer } from 'rollup-plugin-visualizer'

export default defineConfig({
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-react':    ['react', 'react-dom', 'react-router-dom'],
          'vendor-firebase': ['firebase/app', 'firebase/auth'],
          'vendor-socket':   ['socket.io-client'],
          'vendor-sentry':   ['@sentry/react'],
        },
      },
    },
    chunkSizeWarningLimit: 1000,
  },
  plugins: [
    react(),
    visualizer({ filename: 'dist/stats.html', gzipSize: true, brotliSize: true }),
    VitePWA({
      // injectManifest: VitePWA processes public/sw.js (injecting __WB_MANIFEST) instead
      // of generating a workbox-only SW that overwrites the custom one and loses push handlers.
      strategies: 'injectManifest',
      srcDir: 'public',
      filename: 'sw.js',
      registerType: 'autoUpdate',
      includeAssets: ['images/ump-icon.svg', 'images/ump-banner.svg', 'images/ump-logo.png', 'images/market.png', 'images/hostel-hub.png'],
      manifest: {
        name: 'UMP – University Marketplace',
        short_name: 'UMP',
        description: 'The student marketplace for UNILAG — buy, sell, rent, and discover.',
        theme_color: '#f97316',
        background_color: '#ffffff',
        display: 'standalone',
        orientation: 'portrait-primary',
        scope: '/',
        start_url: '/',
        categories: ['shopping', 'education'],
        icons: [
          {
            // SVG with full-bleed background — safe for both any-shape and maskable masks
            src: 'images/ump-icon.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any maskable',
          },
          {
            // PNG fallback for platforms that do not support SVG icons
            // purpose is intentionally "any" only — maskable requires a guaranteed
            // safe zone which a single-size PNG cannot reliably provide
            src: 'images/ump-logo.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'images/ump-logo.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
        ],
        shortcuts: [
          {
            name: 'Marketplace',
            short_name: 'Market',
            url: '/market',
            icons: [{ src: 'images/market.png', sizes: '96x96' }],
          },
          {
            name: 'My Orders',
            short_name: 'Orders',
            url: '/orders',
            icons: [{ src: 'images/ump-icon.svg', sizes: 'any', type: 'image/svg+xml' }],
          },
          {
            name: 'Hostels',
            short_name: 'Hostels',
            url: '/hostel',
            icons: [{ src: 'images/hostel-hub.png', sizes: '96x96' }],
          },
        ],
      },
      injectManifest: {
        // Determines which built assets go into the __WB_MANIFEST precache list.
        // Runtime caching strategies are defined in public/sw.js directly.
        globPatterns: ['**/*.{js,css,html,ico,svg,woff2}'],
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024, // 3 MB
      },
      devOptions: {
        // Keep SW disabled in dev to avoid confusing cache behaviour
        enabled: false,
      },
    }),
  ],
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
      // sitemap.xml/robots.txt are generated by the backend (they need live
      // DB data), not served as static frontend files — proxy them too so
      // they resolve in dev the same way they will in production.
      '/sitemap.xml': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
      '/robots.txt': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
    },
  },
})
